# Generated by Django 4.1.4 on 2022-12-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaApp', '0012_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
